---
- hosts: all
  gather_facts: no

  vars:
    # Provide the OneView IP address and credentials in oneview-config.json
    config: "{{ playbook_dir }}/oneview-config.json"

  vars_files:
    # Provide the names for the server profile template, server profile, and
    # server hardware in infrastructure-config.yml
    - "{{ playbook_dir }}/infrastructure-config.yml"

  tasks:
    - name: Power Off the server hardware
      oneview_server_hardware:
        config: "{{ config }}"
        state: power_state_set
        data:
            name : '{{ server_hardware }}'
            powerStateData:
                powerState: "Off"
                powerControl: "MomentaryPress"
      delegate_to: localhost

    - name: Delete the Server Profile
      oneview_server_profile:
        config: "{{ config }}"
        state: "absent"
        data:
          name: "{{ server_profile }}"
      delegate_to: localhost

    - name: Delete the Server Profile Template
      oneview_server_profile_template:
        config: "{{ config }}"
        state: absent
        data:
          name: "{{ server_profile_template }}"
        params:
          force: True # Supprted only for API version >= 600
      delegate_to: localhost
