---
- hosts: all
  gather_facts: no

  vars:
    - config: "{{ playbook_dir }}/config.json"
    - network_name: network1

  tasks:
    - name: Gather facts about all Ethernet Networks
      oneview_ethernet_network_facts:
        config: "{{ config }}"
      delegate_to: localhost

    - debug: var=ethernet_networks

    - name: Gather facts about an Ethernet Network by name
      oneview_ethernet_network_facts:
        config: "{{ config }}"
        name: "{{ network_name }}"
      delegate_to: localhost

    - debug: var=ethernet_networks.0.uri
