---
- hosts: all
  gather_facts: no

  vars:
    # Provide the OneView IP address and credentials in oneview-config.json
    config: "{{ playbook_dir }}/oneview-config.json"
 
  vars_files:
    # Provide the names for the server profile template, server profile, and
    # server hardware in infrastructure-config.yml
    - "{{ playbook_dir }}/infrastructure-config.yml"
  
  tasks:
    - name: Create a Server Profile from a Server Profile Template
      oneview_server_profile:
        config: "{{ config }}"
        data:
          serverProfileTemplateName: "{{ server_profile_template }}"
          serverHardwareName: "{{ server_hardware }}"
          name: "{{ server_profile }}"
        params:
          force: True
      delegate_to: localhost
      register: result

    - debug: msg="{{ result.msg }}"
    - debug: msg="{{ result }}"

    - name: Power On the server hardware
      oneview_server_hardware:
        config: "{{ config }}"
        state: power_state_set
        data:
            name : "{{ server_hardware }}"
            powerStateData:
                powerState: "On"
                powerControl: "MomentaryPress"
      delegate_to: localhost
